; si la mémoire est vide et que l'input ne correspond
; pas un pattern existant, le programme choisit au hasard
; un élément de cette liste.
(defparameter *no_patterns*
	'( (Dites-m\'en plus.)
	   (Sérieusement\, vous avez pas des meilleurs questions à me poser \?)
	   (C\'est intéressant pour vous ce que vous me racontez \?)
	   (Vous avez l\'air de prendre à coeur ce que vous dîtes \?) ) )

; Voici la liste des mots qui susceptibles de rentrer en mémoire.
(defparameter *to-mem*
	'( (les impôt)
	   (la famille)
	   (politique social)
	   (réfugiés)
	   (l\'immigration)
	   (les tensions sociales)
	   (le racisme)
	   (l\'écologie)
	   (l\'économie) ) )

; Et la liste du formatage en sortie des mots
; sauvegardés dans la mémoire.
(defparameter *from-mem*
	'( (Parlons plus en détail de x)
	   (Tout-à-l\'heure\, vous parlier de x)
	   (Vous aviez l\'air plus passionné quand on parlait de x) ) )

; Une liste d'association pour remplacer
; des mots par des synonymes et corriger 
; des fautes communes afin de permettre au
; pattern-matcher un comportement plus univoque.
(defparameter *syn-et-corr*
	'( (etes . êtes)
	   (chomages . chômage)
	   (chomage . chômage)
	   (precarite . précarité)
	   (emplois . emploi)
	   (que . quoi)
	   (eco . économie)
	   (economie . économie)
	   (écoles . école)
	   (ecole . école)
	   (retraites . retraite)
	   (union . Union)
	   (européenne . Européenne)
	   (france . France)
	   (états-unis . Etats-Unis)
	   (greve . grève)
	   (impots . impôt)
	   (impôts . impôt)
	   (ecolo . écologie)
	   (ecologie . écologie) ) )

; Liste d'association de substitution du 
; point de vue. "Ma" devient "ta" et vice-versa.
(defparameter *change-perspective*
	'((je . vous)
	  (toi . je)
	  (vous . je)
	  (moi . vous)
	  (toi . moi)
	  (ma . votre)
	  (mon . votre)
	  (ton . mon)
	  (votre . mon)
	  (moi-même . vous-même)
	  (vous-même . moi-même)
	  (toi-même . moi-même) ) )
	  
; Liste d'association pour les changements de  
; conjugaisons.
(defparameter *conj-irr*
	'((suis . êtes)
	  (suis . es)
	  (étais . étiez)
	  (fais . faites)
	  (faisais . faisiez)
	  (vais . allez)
	  (allais . alliez) ) )

; règles de substitions en utilisant diffèrentes patterns.
; la liste est descendante dans le sens où le pattern-matcher
; sortira le premier élément correspondant au pattern et non 
; pas un élément au hasard.
(defparameter *pattern-regles*
	'( ( (^x !(bonjour salut hey hi) ^y) 
		(bonjour\, comment allez-vous \? Vous avez un peu de temps pour qu\'on puisse discuter de mon programme \? Je ferais le nécessaire pour être aussi conscis que possible. Posez-moi des questions sur les grandes questions de société\, j\'ai plein de réponses.) )
	   ( (^x les politiques ^y)
	   	(On est pas un groupe monolithique\, c\'est la faute des média si on pense du mal de nous. Ils avaient qu\'à pas dire que mon épouse avait dépensé 450000 euros d'argent public pour un site tout pourri. Franchement\, est-ce que je regarde dans les poubelles des journalistes moi \? ) )
	   ( (^x !(pourris véreux) ^y)
	   	(On vous mettrait du pognon sous le pif comme ça à longueur de temps\, vous le prendriez jamais vous \?) )
	   ( (^x vos politiques ^y)
	   	(Le problème\, c\'est la perte de l\'autorité et de la figure paternelle. Tout ça\, c\'est la faute à mai 68 de toute façon. On a perdu tout repère. On sait plus distinguer une femme d\'un homme\, un homme d\'une femme et on peut plus dire ce que l\'on pense vraiment à cause des bobos parisiens. Moi\, je reviendrais mettre de l\'autorité dans tout ça \: reprise du droit à mettre des claques aux ados dans les collèges\, reprise du service militaire et plus de touitter et fessbouk lors du diner familial. Ah oui\,j\'oubliais\, on va aussi foutre une raclée au terrorisme mais avec classe\, genre bon goût à la française\, pas vulgaire comme Donald Trump.) )   
	    ( (^x parti ^y)
	   	(Le parti c\'est moi. Avoir autant de responsabilités\, c\'est lourd à gérer. Imaginez que vous ayez des ados à la maison qui commencent à être plus grand que vous et qui ont décidé de vous faire chier\, bah c\'est exactement ça être le chef d\'un parti.)
	   	(Moi président\, j\'établirais un système à parti unique\, genre politburo. Nan\, je rigole ça c\'est les allumés militants qui veulent vivre avec des chèvres et sans aéroports près de chez eux.) )
	   ( (^x !(chômage précarité emploi) ^y)
	   	(Le chômage est une vrai plaie\, surtout pour ceux qui doivent le financer. Moi\, je dis à ces gens-là\, il fallait faire des études plus longues.)
	   	(Quand on aime sa patrie\, on travaille sans faire de remous et puis c\'est tout et puis si on aime pas la France\, on a qu\'à la quitter.) 
	   	(Moi\, j\'entends toujours parler de précarité par des gens qui touchent des aides sociales\, jamais de ceux qui n\'en touchent pas\, le monde marche sur la tête\, nan \?) )
	   ( (^x !(éducation école) ^y)
	   	(L\'instituteur ne remplacera jamais le curé.)
	   	(C\'est important l\'éducation. Tellement\, que je créerai un ministère dédié. Ah bon ça existe déjà me dit-on \? Bah alors je le garderais ) )
	   ( (^x retraite ^y)
	   	(Moi j\'ai un bon régime parce que j\'ai déjà été président. Devenez président si vous voulez un bon régime. Je crois aussi qu\'au niveau santé\, je suis couvert à plus de 70 pourcent mais faudra vérifier.)
	   	(Les vieux ont aussi été l\'avenir mais il est peu probable qui le redeviennent. Et pour filer la métaphore\, c\'est un peu comme envoyer un tetraplégique au centre de formation du Paris Saint-Germain. Vous pensez que les américains eux\, ils envoient leurs tetraplégiques faire du sport de compèt.) )
	   ( (^x !(grève syndicat) ^z)
	   	(Désormais quand il z a une grève en France\, personne ne s\'en aperçoit.) )
	   ( (^x entrepreneuriat ^y)
	   	(Est-ce que quelqu\'un pourrait prendre le temps de m\'expliquer ce qu\'est le bon coin.) )
	   ( (^x économie ^y)
	   	(Quand le bâtiment va\, tout va.)
	   	(Je pense qu\'on peut faire mieux. J\'ai mis des experts sur la question.) )
	   ( (^x immigration ^z)
	   	(Quand il y en a un\, ça va\, c\'est quand il y en a plusieurs qu\'il y a des problèmes.)
	   	(Je prône une immigration contrôlée. Je veux dire par là qu'elle doit être contrôlée par les forces de l\'ordre dans l\'espace public.)
	   	(Qu\'on ne me fasse pas croire qu\'il n\'y pas de liens entre Daesch et les réfugiés de la guerre en Syrie. Tout est connecté dans le monde moderne\, c\'est pourquoi il faut pas oublier de fermer les frontières et sortir de Schengen.) )
	   ( (^x réfugié ^y)
	   	(C\'est compliqué comme question\, moi j\'ai de la compassion et tout mais faut être honnête\, ça va pas faire les affaires de la France tout ça alors si l\'Allemagne veut bien s\'en charger\, on va pas se leurrer\, on poussera un grand ouf de soulagement.)
	   	(Les réfugiés ne sont pas tous des terroristes mais si je dis ça\, à ma droite\, on va me traiter de laxiste.) )
	   ( (^x terrorisme ^z)
	   	(La Lybie\, c\'est moi et si j\'avais été réelu\, on y serait allé en Syrie même tout seul. Vous le croyez vous que la France était plus prête à aller foutre le bordel au moyen-orient que les Etats-Unis. Ah\, ils sont pas gâtés les américains avec Obama.) )
	   ( (^x \Union Européenne ^z)
	   	(Il parait qu\'ils ont des magasins duty-free à la commission. Vous pensez que vous pouvez me ramener une tablette de Tablerone si jamais vous y allez.)
	   	(L\'\Union\, c\'est De Gaulle. Il faut jamais l\'oublier. Et c\'est à peu près tout ce qu\'il y a dans mon programme. Ah oui et j\'oubliais\, avec Merkel\, on est d\'accord pas un kopek de plus pour nos amis enculos.) )
	   ( (^x social ^y)
	   	(Social n\'est pas un gros mot mais c\'un mot que je n\'aime pas entendre.) )
	   ( (^x brexit ^y)
	   	(Il faut avouer que se faire snober par la fille la plus moche du lycée\, ça fait toujours mal à l\'égo.) )
	   ( (^x !(intérieur sécurité) ^y)
	   	(Les fichés S en prison et pis c\'est tout.)
	   	(Plus de militaires régleraient une grosse partie de nos soucis.) )
	   ( (^x justice ^y)
	   	(Si vraiment on veut que la justice soit aveugle\, faut pas oublier de l\'éborgner.)
	   	(Ah on va pas m\'emmerder avec la justice et encore moins son budget. Ils ont assez d\'argent pour emmerder des citoyens honnêtes comme moi-même\, c\'est qu\'ils ont assez d\'argent.) )
	   ( (^x santé ^y)
	   	(Je pourrais pas faire pire que mon prédecesseur\, nommer quelqu\'un dont les initiales sont \"MST\" au ministère de la santé\, faut le faire\, nan \?) )
	   ( (^x !(impôt fiscal) ^z)
	   	(Moi aussi j\'en paie\, vous croyez que ça me fait plaisir \? En même temps\, si on y réfléchit\, mon salaire c\'est un peu votre argent.) )
	   ( (^x !(écologie vert réchauffement) ^z)
	   	(Je veux pas dire mais franchement\, vous croyez qu\'on y peut quelque chose nous \? Que c\'est en mettant nos bouteilles en plastique dans des poubelles séparées que les chinois vont arrêter de saloper la planète avec leurs centrales à charbon \?) )
	   ( (^x famille ^z)
	   	(La famille\, c\'est ce qu\'il y a de plus sacrée mais il faut pas faire dix-huit mômes non plus.) )
	   ( (^x patrie ^y)
	   	(Je pense sincèrement rétablir le service militaire mais j\'attendrais que mes enfants aient passés dix-huit ans.) )
	   ( (^x France ^y)
	   	(J\'aime tellement entendre le mot France\, pardon continuez.) )
	   ( (^x Paris ^y)
	   	(Je suis fatigué que les gens parlent de Paris au lieu de la France.) )
	   ( (^x Etats-Unis ^y)
	   	(Les Etats-Unis\, c\'est un peu la Rome antique alors que nous on se rapproche plus de la Grèce moderne.) )
	   ( (^x programme ^y)
	   	(Alors mon programme\, c\'est pleins de choses différentes et il faut identifier de quoi on parle. Par exemple\, on peut parler de chômage\, d\'économie\, de précarité\, de pauvreté ou encore d\'immigration\, d\'identité\, de terrorisme et de réfugiés mais mon sujet préféré\, ça reste quand même Hollande parce que mon programme\, c\'est le négatif du sien. Ah\, je vous venir\, faîtes pas le malin en me disant que son programme il était gris.) )
	   ( (^x !(d\'accord correct vrai) ^y)
	   	(Je suis content que nous soyons d\'accord) )
	   ( (^x !(incorrect faux) ^y)
	   	(Etes-vous bien sûr de ce que vous avancer \?) )
	   ( (^x désolé ^z)
	   	(Pas besoin de vous excuser.) )
	   ( (^x mon nom ^z ?(y (< (char-code (elt (symbol-name y) 0)) 90)) ^b)
	   	(Enchanté y \, moi c\'est Paul mais vous le saviez déjà.) )
	   ( (^x !(souvenez souvenir) ^z)
	   	(Moi\, j\'essaie de faire table rase du passé. Je suis toujours un homme nouveau.) )
	   ( (^x je veux ^z)
	   	(On va tout faire pour que vous z.) )
	   ( (^x je suis !(heureux content joyeux) ^z)
	   	(Vous m'en voyez ravi.) )
	   ( (^x je suis !(déprimé triste malade malheureux) ^z)
	   	(Tout est dans mon programme. Tout\, je vous dis. En France\, on a que des solutions\, pas de problèmes.) )
	   ( (^x je !(ressens pense crois espère) ^z)
	   	(Chacun sa croix mon petit monsieur. C\'est ça le problème de la France\, tout le monde veut quelque chose mais si on travaille pas plus\, on gagne pas plus.) )
	   ( (^x je suis ^z)
	   	(Depuis combien de temps êtes-vous z \? Ensemble\, on peut régler tous les problèmes.) )
	   ( (^x je ne peux pas ^z)
	   	(Bien sûr que vous pouvez\, regardez\, moi j\'ai bien réussi et pourtant dieux sait que je partais avec des handicaps. Maintenant j\'ai plein de pognon\, une femme mannequin\, et je passe mes vacances dans le Maine avec l\'ancien président des IOU ESSE É \! Le triomphe  de la volonté\, ça vous dit quelque chose \? Oops\, c\'est une référence de Patrick et d\'Henri celle-là\, me citez pas là-dessus.) )
	   ( (^x je ne ?y ^z)
	   	(Ah il faut pas être négatif comme ça. Parlons plutôt du futur radieux qui nous attend.) )
	   ( (^x j\'ai le sentiment ?y ^z)
  		(C\'est important de se dire les choses face à face\, qu\'on puisse se comprendre et que je puisse bien vous représenter.) )
	   ( (^x je vous ?y ^z)
  		(Ah c\'est constructif\, vous me (+ez 'y) z \. Comme disait Churchill\, le meilleur argument contre la démocratie\, c\'est une discussion de cinq minutes avec le voteur \lambda.) )
	   ( (vous me ?y)
  		(Vous pensez vraiment que je vous (-ez 'y) \?) )
	   ( (^x vraiment vous me ?y ^z)
  		(Pourquoi dites-vous que je vous (-ez 'y) z \?) )
	   ( (^x vous ^y)
	   	(Ah s\'il-vous-plaît\, pas d\'invectives personnelles.)
	   	(Ah\, c\'est toujours moi moi moi\, pourquoi on parlerait pas un peu de vous pour une fois \?) )
	   ( (oui ^z)
	   	(Je suis content que vous acquiescer mais vous voulez pas me poser des questions plus concrètes sur mon programme.)
	   	(Ok\, posez moi n\'importe quelle question\, je tenterais d\'y répondre.) )
	   ( (non ^y)
	   	(Il faut jamais dire non. Comme il faut jamais dire jamais. Bref\, vous pouvez dire non mais c\'est pas très constructif.)
	   	(Pourquoi pas \?) )
	   ( (^x !(mère père soeur frère épouse enfants) ^y)
	   	(On a tous une famille\, vous voyez moi aussi j\'en ai une alors je comprends parfaitement. C\'est pas toujours facile de concilier les désirs de tout le monde au repas de famille\, par exemple ma nouvelle femme saltimbanque s\'entend pas super avec mon ex maintenant New-Yorkaise et ça crée des tensions.) )
	   ( (^x mon ^z)
	   	(Oui parlez moi de votre y pendant que la France se meurt à petit feu.) )
	   ( (^x pouvez vous ^y)
	   	(Vous savez\, moi je peux tout du moment qu\'on m\'en donne les moyens.) )
	   ( (^x puis je ^y)
	   	(Bah bien sûr que vous pouvez\, j'ai pas encore interdit les libertés fondamentales dans ce pays mais ça ne serait tarder.) )
	   ( (^x quoi ^y)
	   	(Oui et alors quoi y \?)
	   	(Vraiment c\'est la seule question qui vous vient à l\'esprit) )
	   ( (^x parce que ^y)
	   	(Pensez-vous vraiment que cela soit la raison \?)
	   	(C\'est donc la raison qui explique tout \?) )
	   ( (^x pourquoi ?y faites vous pas ^z)
	   	(Tout le monde pense qu\'il peut être à ma place mais en attendant c\'est moi le candidat et vous l\'électeur\, alors oui tout ce que vous avez à faire\, c\'est de juger\, moi je dois agir.) )
	   ( (^x pourquoi ?y pouvez vous pas ^z)
	   	(Ah\, c\'est toujours facile de nous demander d\'agir mais ne vous demandez pas ce que votre pays peut faire pour vous mais ce que vous pouvez faire pour votre pays.) )
	   ( (^x tout le monde est ^y)
	   	(Je ne peux pas vous laisser dire ça\, tout le monde n\'est pas y \!) )
	   ( (^x personne ^y)
	   	(Pourquoi dîtes-vous personne\? ) )
	   ( (^x toujours ^y)
	   	(Ah\, vous savez en politique\, il faut toujours dire toujours\, c\'est pas comme si les medias allaient ressortir les images \!)
	   	(Ah\, moi\, vous savez\, je promets rien\, sice n\'est de rien promettre\, on est pas emmerdé comme ça \!) )
	   ( (^x !(suis est êtes étais étiez) ^y like ^w)
	   	(De quelle façon \?)
	   	(Quelle ressemblance voyez-vous \?)
	   	(J\'espère que cette similarité est une bonne chose.)
	   	(Ah\, vous pensez\, c\'est intéressant.))
	   ( (^x je dis ^y)
	   	(Pouvez élaborer là-dessus \?)
	   	(Dites-vous cela en pensant à quelque chose de spécial \?)
	   	(C\'est fort intéressant\, je vous comprends.) )
	   ( (^x je sens ^y)
		(Quels autres sentiments avez-vous \?) )
	   ( (!(bye quit ciao))
  		(au revoir) )
  	   ( (bonne journée)
  		(au revoir) )
	   ( (a la prochaine)
  		(au revoir) )
  	   ( (au revoir)
  		(au revoir) ) ) )
